# Generated by Django 5.1.2 on 2024-10-18 14:56

import django.core.validators
import fruitipedia.commoms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.commoms.validators.first_letter_validator])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia.commoms.validators.first_letter_validator])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18)),
            ],
        ),
    ]
