# Generated by Django 5.1.2 on 2024-10-18 14:56

import django.core.validators
import django.db.models.deletion
import fruitipedia.commoms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.commoms.validators.first_letter_validator, fruitipedia.commoms.validators.only_letters])),
                ('fruit_image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
